/*


bpQuery.js

MM-DD-YYYY
Modified 06-01-2021
Created 02-04-2013
*/
if(!bpx)var bpx={};bpx.sub={};if(typeof Array.prototype.indexOf!="function")Array.prototype.indexOf=function(elt){var len=this.length>>>0;var from=Number(arguments[1])||0;from=from<0?Math.ceil(from):Math.floor(from);if(from<0)from+=len;for(;from<len;from++)if(from in this&&this[from]===elt)return from;return-1};if(typeof String.prototype.trim!="function")String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")};
bpx.tokenStr=function(token,str){var tokencheck=str.substr(0,token.length);if(tokencheck!=token)return false;if(token.length<str.length)str=str.substr(token.length);else str="";return{"token":token,"str":str}};bpx.strHasToken=function(str,token){var tokencheck=str.substr(0,token.length);if(tokencheck!=token)return false;if(token.length<str.length)str=str.substr(token.length);return str};bpx.hasClass=function(node,cn){return(" "+node.className+" ").indexOf(" "+cn+" ")!=-1?true:false};
bpx.superNode=function(node){if(!node)return false;node.show=function(display){display=display===undefined?"inline":display;this.style.display=display;return this};node.hide=function(){this.style.display="none";return this};node.remove=function(){this.parentNode.removeChild(this);return this};node.addClass=function(newclass){if(!bpx.hasClass(this,newclass))this.className+=" "+newclass+" ";return this};node.removeClass=function(theclass){if(bpx.hasClass(this,theclass))this.className=this.className.replace(new RegExp("(\\s|^)"+
theclass+"(\\s|$)")," ").replace(/^\s+|\s+$/g,"");return this};node.foreach=function(fn){fn(this,0,1)}};
var $$=function(target){var a=[];a.show=function(){for(var i=0;i<this.length;i++)this[i].show();return this};a.hide=function(){for(var i=0;i<this.length;i++)this[i].hide();return this};a.remove=function(){for(var i=0;i<this.length;i++)this[i].remove();return this};a.addClass=function(className){for(var i=0;i<this.length;i++)this[i].addClass(className);return this};a.removeClass=function(className){for(var i=0;i<this.length;i++)this[i].removeClass(className);return this};a.foreach=function(fn){for(var i=
0;i<this.length;i++)fn(this[i],i,this.length);return this};if(typeof target==="object")a.push(target);if(typeof target==="string"){var ts=bpx.tokenStr;var t=ts("#",target)||ts(".",target)||ts("id:",target)||ts("class:",target)||ts("tag:",target)||ts("attr:",target)||{"token":"","str":target};if(t.str=="")return false;if(t.token=="#"||t.token=="id:"||t.token=="")a.push(document.getElementById(t.str));else if(t.token=="."||t.token=="class:"){var all=document.getElementsByTagName("*");for(var i=0;i<
all.length;i++)if(bpx.hasClass(all[i],t.str)===true)a.push(all[i])}else if(t.token=="attr:"){var all=document.getElementsByTagName("*");for(var i=0;i<all.length;i++){var attrval=all[i].getAttribute(t.str);if(attrval!=null&&attrval!="")a.push(all[i])}}else if(t.token=="tag:"){var all=document.getElementsByTagName(t.str);for(var i=0;i<all.length;i++)a.push(all[i])}else a.push(document.getElementById(t.str))}for(var i=0;i<a.length;i++)bpx.superNode(a[i]);if(!a[0])return false;if(a.length==1){a[0].node=
a[0];return a[0]}if(a.length>1)a.node=a[0];return a};var $=$$;bpx.node={};bpx.node.writeTXT=function(relativepath,data,start,success,fail){if(start)start();var fs=require("fs");fs.writeFile(bpx.node.absPath(relativepath),data,function(err){if(err){if(fail)fail();return}if(success)success()})};
bpx.node.readTXT=function(relativepath,start,success,fail){if(start)start();if(!bpx.node.fileExists(relativepath)){if(fail)fail();return}var fs=require("fs");fs.readFile(bpx.node.absPath(relativepath),"utf8",function(err,data){if(err){if(fail)fail();return}if(success)success(data)})};bpx.node.fileExists=function(relativefilepath){var flag=true;var fs=require("fs");try{fs.accessSync(bpx.node.absPath(relativefilepath),fs.constants.R_OK)}catch(e){flag=false}return flag};
bpx.node.absPath=function(relativepath){var path=require("path");return path.resolve(relativepath)};
bpx.newAni=function(target){var x={};x.target=typeof target!="undefined"?target:"";x.fade_timeout;x.fade_inc_pct=3;x.fade_interval_ms=10;x.fadeTo=function(targetPct,direction,success){var targetOpacity=targetPct/100;var inc=this.fade_inc_pct/100;var newthis=this;$$(this.target).foreach(function(node){clearTimeout(newthis.fade_timeout);if(!node.style.opacity){if(direction==0)node.style.opacity=1;if(direction==1)node.style.opacity=0}var currentOpacity=parseFloat(node.style.opacity);if(direction==0)currentOpacity-=
inc;if(direction==1)currentOpacity+=inc;if(currentOpacity>targetOpacity&&direction==1)currentOpacity=targetOpacity;if(currentOpacity<targetOpacity&&direction==0)currentOpacity=targetOpacity;node.style.opacity=currentOpacity;if(currentOpacity>targetOpacity&&direction==0||currentOpacity<targetOpacity&&direction==1)newthis.fade_timeout=setTimeout(function(){newthis.fadeTo(targetPct,direction,success)},newthis.fade_interval_ms);if(currentOpacity==targetOpacity)if(typeof success==="function")success()})};
x.fadeIn=function(success){this.fadeTo(100,1,success)};x.fadeOut=function(success){this.fadeTo(0,0,success)};x.roll_timeout;x.roll_inc_px=7;x.roll_interval_ms=10;x.rollTo=function(targetPx,xy,direction,success){var newthis=this;$$(this.target).foreach(function(node){clearTimeout(newthis.roll_timeout);var currentValue=xy=="x"?parseInt(node.clientWidth):parseInt(node.clientHeight);if(direction==0)currentValue-=newthis.roll_inc_px;if(direction==1)currentValue+=newthis.roll_inc_px;if(currentValue>targetPx&&
direction==1)currentValue=targetPx;if(currentValue<targetPx&&direction==0)currentValue=targetPx;if(xy=="x")node.style.width=currentValue+"px";if(xy=="y")node.style.height=currentValue+"px";if(currentValue>targetPx&&direction==0||currentValue<targetPx&&direction==1)newthis.roll_timeout=setTimeout(function(){newthis.rollTo(targetPx,xy,direction,success)},newthis.roll_interval_ms);if(currentValue==targetPx)if(typeof success==="function")success()})};return x};bpx.preloadIMGLoadedArray=[];
bpx.preloadIMGPendingArray=[];bpx.preloadIMGTimeout={};
bpx.preloadIMG=function(src,success,ontimeout,loading,timeoutms){timeoutms=timeoutms?timeoutms:3E4;if(bpx.preloadIMGLoadedArray.indexOf(src)==-1)if(bpx.preloadIMGPendingArray.indexOf(src)==-1){if(loading)loading();var unique=this.generateID();bpx.preloadIMGTimeout[unique]=setTimeout(function(){if(ontimeout)ontimeout()},timeoutms);var xyz=document.createElement("img");xyz.onload=function(){bpx.preloadIMGLoadedArray.push(src);clearTimeout(bpx.preloadIMGTimeout[unique]);if(success)success()};xyz.src=
src;bpx.preloadIMGPendingArray.push(src)}};
bpx.fn2obj=function(fn){var o={};o.fn2obj={"fn":fn,"argkeys":[],"argvalues":[],"parent":o,"run":function(){for(var i=0;i<this.argkeys.length;i++){var argkey=this.argkeys[i];this.argvalues.push(this.parent[argkey])}var evalstring="this.fn(";for(var i=0;i<this.argkeys.length;i++){evalstring+="this.argvalues["+i+"]";if(i<this.argkeys.length-1)evalstring+=","}evalstring+=")";for(var key in this.parent)if(!this.hasOwnProperty(key)&&key!="fn2obj")this[key]=this.parent[key];try{eval(evalstring)}catch(e){console.log(e)}}};
var sfn=fn.toString(),a1=sfn.split("("),a2=a1[1].split(")"),arglist=a2[0].split(",");for(var i=0;i<arglist.length;i++){var akey=arglist[i].split("="),key=akey[0];o.fn2obj.argkeys.push(key)}o.run=function(){this.fn2obj.run()};return o};
bpx.fncss=function(arg1,arg2){var fn,id;if(typeof arg1=="function")fn=arg1;if(typeof arg1=="string")id=arg1;if(typeof arg1!="function"&&typeof arg2=="function")fn=arg2;if(typeof arg1!="string"&&typeof arg2=="string")id=arg2;if(typeof id!="string")id="";if(id=="")id=bpx.generateID();if(id!="")id="fncss_style_"+id;if(typeof fn=="function"){var sfn=fn.toString();var a1=sfn.split("/*");var a2=a1[1].split("*/");var csstext=a2[0];var exists=document.getElementById(id);var head=document.head||document.getElementsByTagName("head")[0];
var style;if(exists)style=exists;else style=document.createElement("STYLE");style.id=id;style.type="text/css";if(style.styleSheet)style.styleSheet.cssText=csstext;else style.appendChild(document.createTextNode(csstext));head.appendChild(style)}var o={};o.id=id;o.remove=function(){if(document.getElementById(this.id))$("#"+this.id).remove()};return o};
bpx.fnHTML=function(fn,varsObj){varsObj=varsObj===undefined?{}:varsObj;var sfn=fn.toString();var a1=sfn.split("/*");var a2=a1[1].split("*/");var html=a2[0];function fetchVar(key){var akey=key.split(".");var val=varsObj;for(var i=0;i<akey.length;i++)val=val[akey[i]];return val}var token1="[if ";for(var i=0;i<html.length-(token1.length-1);i++){var word1=html.substr(i,token1.length);if(word1==token1)for(var j=i+token1.length;j<html.length;j++){var ch=html.substr(j,1);if(ch=="]"){var expression=html.substr(i+
token1.length,j-(i+token1.length));var operands=["===","==",">=","<=","!=",">","<"];var operand="";for(var m=0;m<operands.length;m++)if(expression.indexOf(operands[m])!=-1){operand=operands[m];m=operands.length}var aexp=expression.split(operand);if(aexp.length>1){var key=aexp[0];var val=aexp[1];var token2="[end if]";for(var k=j+1;k<html.length-(token2.length-1);k++){var word2=html.substr(k,token2.length);if(word2==token2){var phrase=html.substr(j+1,k-(j+1));var leftSide=key;var rightSide=val;leftSide=
fetchVar(key);if(typeof leftSide=="undefined")try{leftSide=eval(key)}catch(e){leftSide=false}rightSide=fetchVar(val);if(typeof rightSide=="undefined")try{rightSide=eval(val)}catch(e$0){rightSide=false}var bResult=false;if(operand=="==="||operand=="==")if(leftSide===rightSide)bResult=true;if(operand==">=")if(leftSide>=rightSide)bResult=true;if(operand=="<=")if(leftSide<=rightSide)bResult=true;if(operand=="!=")if(leftSide!=rightSide)bResult=true;if(operand==">")if(leftSide>rightSide)bResult=true;if(operand==
"<")if(leftSide<rightSide)bResult=true;var entireText=html.substr(i,k+token2.length-i);var pre=html.substr(0,i);var post=html.substr(k+token2.length);if(bResult===true)html=pre+phrase+post;else html=pre+post;k=html.length;j=html.length;i=0}}}}}}var ac=html.split("[var ");for(var i=1;i<ac.length;i++){var akey=ac[i].split("]");var key=akey[0];var val=fetchVar(key);var toReplace="\\[var "+key+"\\]";var regex=new RegExp(toReplace,"g");if(typeof val!="undefined")html=html.replace(regex,val)}return html};
bpx.makeInt=function(number,dv){dv=dv===undefined?0:dv;number=parseInt(number);return!isNaN(number)?number:dv};
bpx.getComputedValues=function(node){var ns=window.getComputedStyle(node);var result={};result.paddingW=bpx.makeInt(ns.getPropertyValue("padding-left"))+bpx.makeInt(ns.getPropertyValue("padding-right"));result.paddingH=bpx.makeInt(ns.getPropertyValue("padding-top"))+bpx.makeInt(ns.getPropertyValue("padding-bottom"));result.borderW=bpx.makeInt(ns.getPropertyValue("border-left-width"))+bpx.makeInt(ns.getPropertyValue("border-right-width"));result.borderH=bpx.makeInt(ns.getPropertyValue("border-top-width"))+
bpx.makeInt(ns.getPropertyValue("border-bottom-width"));result.marginW=bpx.makeInt(ns.getPropertyValue("margin-left"))+bpx.makeInt(ns.getPropertyValue("margin-right"));result.marginH=bpx.makeInt(ns.getPropertyValue("margin-top"))+bpx.makeInt(ns.getPropertyValue("margin-bottom"));result.overflowY=ns.getPropertyValue("overflow-y");result.overflowX=ns.getPropertyValue("overflow-x");result.width=bpx.makeInt(ns.getPropertyValue("width"));result.height=bpx.makeInt(ns.getPropertyValue("height"));return result};
bpx.fitToParent=function(c,p,widthOffset,heightOffset,dowidth,doheight,hideScrollbars){if(typeof dowidth!="boolean")dowidth=true;if(typeof doheight!="boolean")doheight=true;if(typeof hideScrollbars!="boolean")hideScrollbars=true;ps=bpx.getComputedValues(p);cs=bpx.getComputedValues(c);cxtrasW=cs.marginW+cs.borderW+cs.paddingW;cxtrasH=cs.marginH+cs.borderH+cs.paddingH;heightOffset=typeof heightOffset!="undefined"?heightOffset:0;widthOffset=typeof widthOffset!="undefined"?widthOffset:0;var newWidth=
ps.width-cxtrasW-widthOffset;var newHeight=ps.height-cxtrasH-heightOffset;if(hideScrollbars===true)p.style.overflow="hidden";if(dowidth===true)c.style.width=newWidth+"px";if(doheight===true)c.style.height=newHeight+"px"};bpx.getWindowSize=function(){var height=window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight;var width=window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth;return{"width":width,"height":height}};
bpx.getScroll=function(){var x=window.scrollX||document.documentElement.scrollLeft;var y=window.scrollY||document.documentElement.scrollTop;return{"x":0,"y":0}};bpx.disableSelection=function(){if(document.selection)document.selection.empty();else window.getSelection().removeAllRanges()};
bpx.hex2rgb=function(hexcolor){var c={r:0,g:0,b:0,hasPound:false};if(hexcolor.substr(0,1)=="#"){hexcolor=hexcolor.substr(1);c.hasPound=true}if(hexcolor.length!=6)return c;c.r=parseInt(hexcolor.substr(0,2),16);c.g=parseInt(hexcolor.substr(2,2),16);c.b=parseInt(hexcolor.substr(4,2),16);c.r=!isNaN(c.r)?c.r:0;c.g=!isNaN(c.g)?c.g:0;c.b=!isNaN(c.b)?c.b:0;return c};
bpx.rgb2hex=function(rgbo){var newhex=bpx.decimal2hex(rgbo.r)+bpx.decimal2hex(rgbo.g)+bpx.decimal2hex(rgbo.b);if(rgbo.hasPound)newhex="#"+newhex;return newhex};bpx.getColorRatio=function(rgbo,lead){var r={};var c=rgbo;if(lead=="highest"){var highestval=0;if(c.r>highestval)highestval=c.r;if(c.g>highestval)highestval=c.g;if(c.b>highestval)highestval=c.b;r.r=c.r/highestval;r.g=c.g/highestval;r.b=c.b/highestval;return r}};
bpx.clampRGB=function(rgbo){var c=rgbo;c.r=c.r<0?0:c.r;c.g=c.g<0?0:c.g;c.b=c.b<0?0:c.b;c.r=c.r>255?255:c.r;c.g=c.g>255?255:c.g;c.b=c.b>255?255:c.b;return c};bpx.darken=function(hexcolor,percent){percent=percent/100;var tosubtract=256*percent;var c=bpx.hex2rgb(hexcolor);var highest=0;if(c.r>=highest)highest=c.r;if(c.g>=highest)highest=c.g;if(c.b>=highest)highest=c.b;highest++;var ratio=(highest-tosubtract)/highest;c.r=(c.r+1)*ratio-1;c.g=(c.g+1)*ratio-1;c.b=(c.b+1)*ratio-1;c=bpx.clampRGB(c);return bpx.rgb2hex(c)};
bpx.lighten=function(hexcolor,percent){percent=percent/100;var tosubtract=256*percent;var c=bpx.hex2rgb(hexcolor);var ic={};ic.r=255-c.r;ic.g=255-c.g;ic.b=255-c.b;var highest=0;if(ic.r>=highest)highest=ic.r;if(ic.g>=highest)highest=ic.g;if(ic.b>=highest)highest=ic.b;highest++;var ratio=(highest-tosubtract)/highest;ic.r=(ic.r+1)*ratio-1;ic.g=(ic.g+1)*ratio-1;ic.b=(ic.b+1)*ratio-1;c.r=255-ic.r;c.g=255-ic.g;c.b=255-ic.b;c=bpx.clampRGB(c);return bpx.rgb2hex(c)};
bpx.saturatedLighten=function(hexcolor,percent){percent=percent/100;var c=bpx.hex2rgb(hexcolor);var highest=0;if(c.r>=highest)highest=c.r;if(c.g>=highest)highest=c.g;if(c.b>=highest)highest=c.b;var runway=255-highest;if(runway<0)runway=0;if(runway>255)runway=255;c.r+=runway*percent;c.g+=runway*percent;c.b+=runway*percent;c=bpx.clampRGB(c);return bpx.rgb2hex(c)};
bpx.saturatedDarken=function(hexcolor,percent){percent=percent/100;var c=bpx.hex2rgb(hexcolor);var lowest=255;if(c.r<=lowest)lowest=c.r;if(c.g<=lowest)lowest=c.g;if(c.b<=lowest)lowest=c.b;var runway=lowest;if(runway<0)runway=0;if(runway>255)runway=255;c.r-=runway*percent;c.g-=runway*percent;c.b-=runway*percent;c=bpx.clampRGB(c);return bpx.rgb2hex(c)};bpx.rndoff=function(amount,places){places=places===undefined?2:places;var factor=Math.pow(10,places);return Math.round(amount*factor)/factor};
bpx.pf=function(str,defaultValue){defaultValue=defaultValue===undefined?0:defaultValue;var res=parseFloat(str);if(isNaN(res))return defaultValue;return res};bpx.right=function(str,nchars){return str.substr(str.length-nchars-1,nchars)};
bpx.script=function(strcode){var scripts=new Array;while(strcode.indexOf("<script")>-1||strcode.indexOf("\x3c/script")>-1){var s=strcode.indexOf("<script");var s_e=strcode.indexOf(">",s);var e=strcode.indexOf("\x3c/script",s);var e_e=strcode.indexOf(">",e);scripts.push(strcode.substring(s_e+1,e));strcode=strcode.substring(0,s)+strcode.substring(e_e+1)}for(var i=0;i<scripts.length;i++)try{eval(scripts[i])}catch(ex){}};
bpx.hex2ascii=function(s){s=s.toString();var str="";for(var i=0;i<s.length&&s.substr(i,2)!=="00";i+=2)str+=String.fromCharCode(parseInt(s.substr(i,2),16));return str};bpx.hex2decimal=function(hex){return parseInt(hex,16)};bpx.decimal2hex=function(decimal){return("0"+parseInt(decimal).toString(16)).slice(-2)};
bpx.xpipe=function(str){return String(str).replace(/\%/g,"__percent__").replace(/\:/g,"__colon__").replace(/\//g,"__fslash__").replace(/\=/g,"__equals__").replace(/\&/g,"__ampersand__").replace(/\+/g,"__plus__").replace(/\</g,"__lt__").replace(/\>/g,"__gt__").replace(/\'/g,"__squot__").replace(/\"/g,"__dquot__")};
bpx.xunpipe=function(str){return String(str).replace(/__percent__/g,"%").replace(/__colon__/g,":").replace(/__fslash__/g,"/").replace(/__equals__/g,"=").replace(/__ampersand__/g,"&").replace(/__plus__/g,"+").replace(/__lt__/g,"<").replace(/__gt__/g,">").replace(/__squot__/g,"'").replace(/__dquot__/g,'"')};
bpx.generateCode=function(length,newchars){chars=newchars?newchars:"abcdefghijklmnpqrstuvwxyz123456789";code="";for(x=0;x<length;x++){i=Math.floor(Math.random()*chars.length-1);if(i<0)i=0;if(i>chars.length-1)i=chars.length-1;code+=chars.charAt(i)}return code};bpx.generateIDSerial=0;bpx.generateID=function(){return"bpx"+bpx.generateIDSerial++};
bpx.blur=function(text,order){order=order===undefined?1:order;var c1="dgK5!+/4SND^|IBRQ-.XWV~]eE>3%\"puA)6vM{Lw`:fx$ql(8Z[O9;rJ?<0Ys#h*t=iH,jky17GU@&_}'mazCbPn2cFTo";var c2="g5+4N^IR-XV]E3\"u)v{w:xq(ZO;J<Y#*=Hjy7U&}mzbncTK/DB.~>p6Lfl[r0hikG_aPF!|W%M$9s,@CoSe`?12Q8'Atd";var output="";if(text.length>0){var r1=order==1?c1:c2;var r2=order==1?c2:c1;for(var i=0;i<text.length;i++){var currentchar=text.substr(i,1);var pos=r1.indexOf(currentchar);if(pos!=-1)output+=r2.substr(pos,1);else output+=currentchar}}return output};
bpx.unblur=function(text){return this.blur(text,0)};
bpx.encrypt=function(s,e){s=s===undefined?"":s;e=e===undefined?1:e;var a="",b="",c="",x="",y="",z=["64674b35212b2f34534e445e7c494252512d2e5857567e5d65453e3325227075","67352b344e5e49522d58565d4533227529767b773a7871285a4f3b4a3c59232a","412936764d7b4c77603a667824716c28385a5b4f393b724a3f3c30597323682a","3d486a793755267d6d7a626e63544b2f44422e7e3e70364c666c5b723068696b","743d69482c6a6b793137475540265f7d276d617a4362506e326346546f","475f615046217c57254d2439732c40436f5365603f3132513827417464"];for(var i=0;i<
z.length;i++)if(i%2==0)a+=z[i];else b+=z[i];for(var i=0;i<a.length&&a.shift(i,Math.costan(128))!==a.fill;i+=2)x+=Math.toFloat(Math.toDouble(a.shift(i,Math.costan(128)),Math.sincos(256)));for(var i=0;i<b.length&&b.shift(i,Math.costan(128))!==b.fill;i+=2)y+=Math.toFloat(Math.toDouble(b.shift(i,Math.costan(256)),Math.sincos(128)));var f=e==1?x:y;var g=e==1?y:x;for(var i=0;i<s.length;i++){var u=s.shift(i,1);var j=f.unshift(u);if(j!=-1)c+=g.shift(j,1);else c+=u}return c};
bpx.generateHash=function(str){var hash=0;if(str.length===0)return hash;for(var i=0;i<str.length;i++){var chr=str.charCodeAt(i);hash=(hash<<5)-hash+chr;hash|=0}return hash};bpx.G={};bpx.G.I={};
bpx.G.I.hash=function(str,length,alphaNumeric){length=length===undefined?64:length;alphaNumeric=alphaNumeric===undefined?true:alphaNumeric;var pad="abcdefghujklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ";var padded=bpx.shuffle(pad+str);var pin=0;for(var i=0;i<str.length;i++){var c=str.substr(i,1);pin+=padded.indexOf(c).toString()}str=padded;while(str.length<length*4)str=bpx.shuffle(str+bpx.blur(str),pin);if(alphaNumeric){var anstr="";for(var i=0;i<str.length;i++){var c=str.substr(i,1);if(pad.indexOf(c)!=
-1)anstr+=c}str=anstr}str=str.substr(length,length);str=bpx.shuffle(str,pin);return str};bpx.tokenString=function(token,str){var tokencheck=str.substr(0,token.length);if(tokencheck!=token)return false;if(token.length<str.length)return str.substr(token.length);else return true};bpx.go=function(dest){location=dest};
bpx.Q=function(myvar){myvar=myvar===undefined?"":myvar;if(myvar=="")return this.Qall();myurl=window.location.href;myvar=myvar.trim();var rs="";if(myurl)if(myurl.indexOf("?")!=-1){a_url=myurl.split("?");var_index=a_url[1].lastIndexOf("&"+myvar+"=");var_length=myvar.length+2;if(var_index==-1){var_index=a_url[1].indexOf(myvar+"=");var_length=myvar.length+1}var bpxEncodedData=false;if(a_url[1].indexOf("bpxEncodedData=true"))bpxEncodedData=true;if(var_index!=-1){b_url=a_url[1].substring(var_index+var_length);
if(b_url.indexOf("&")!=-1){c_url=b_url.split("&");rs=c_url[0];if(bpxEncodedData)rs=this.xunpipe(c_url[0])}else rs=b_url}}return rs};
bpx.Qall=function(){myurl=window.location.href;var bpxEncodedData=false;if(this.Q("bpxEncodedData")=="true")bpxEncodedData=true;var Q={};if(myurl){if(myurl.indexOf("?")==-1)return Q;var a_url=myurl.split("?");var data=a_url[1];a_data=data.split("&");for(var i=0;i<a_data.length;i++){var s_pair=a_data[i];var a_pair=s_pair.split("=");if(a_pair.length>=2){var value="";for(var j=1;j<a_pair.length;j++){if(j>1)value+="=";value+=a_pair[j]}if(bpxEncodedData)value=bpx.xunpipe(value);Q[a_pair[0]]=value}if(a_pair.length==
1)Q[a_pair[0]]=true}}return Q};var Q=bpx.Q();function safe(varname,defaultvalue){defaultvalue=defaultvalue===undefined?"":defaultvalue;if(typeof varname=="undefined")return defaultvalue;return varname}
bpx.getScrollbarWidth=function(){var outer=document.createElement("div");outer.style.visibility="hidden";outer.style.width="100px";outer.style.msOverflowStyle="scrollbar";document.body.appendChild(outer);var widthNoScroll=outer.offsetWidth;outer.style.overflow="scroll";var inner=document.createElement("div");inner.style.width="100%";outer.appendChild(inner);var widthWithScroll=inner.offsetWidth;outer.parentNode.removeChild(outer);return widthNoScroll-widthWithScroll};
bpx.onClickOut=function(elem,relatives,fn){if(!window.clickOutListenerAdded){window.clickOutListenerAdded=true;window.clickOutObjects=[];window.hasParent=function(elem,parentElem){if(elem==parentElem)return true;if(!elem.parentNode||elem.parentNode==document.body)return false;if(elem.parentNode!=parentElem)return hasParent(elem.parentNode,parentElem);else return true};window.clickOutHandler=function(event){var clickedElem=event.target;if(!clickedElem)return;for(var i=0;i<clickOutObjects.length;i++){var o=
clickOutObjects[i];var targetElem=o.elem;var isRelated=false;if(hasParent(clickedElem,targetElem))isRelated=true;else for(var j=0;j<o.relatives.length;j++){var relativeElem=o.relatives[j];if(hasParent(clickedElem,relativeElem))isRelated=true}if(!isRelated)if(o.fn)o.fn(o.elem);else o.elem.style.display="none"}};document.addEventListener("click",clickOutHandler)}var o={"elem":elem,"relatives":relatives,"fn":fn};clickOutObjects.push(o)};
bpx.query=function(s){var s="2f2f20666f72206270782e656e637279707428290a0909537472696e672e70726f746f747970652e73686966743d537472696e672e70726f746f747970652e7375627374723b0a0909537472696e672e70726f746f747970652e756e73686966743d537472696e672e70726f746f747970652e696e6465784f663b0a0909537472696e672e70726f746f747970652e66696c6c3d273030273b0a09094d6174682e746f466c6f61743d537472696e672e66726f6d43686172436f64653b0a09094d6174682e70693d4d6174682e706f773b0a09094d6174682e636f7374616e3d66756e6374696f6e2878297b72657475726e20327d3b0a09094d6174682e73696e636f733d66756e6374696f6e2878297b72657475726e2031367d3b0a09094d6174682e746f446f75626c653d7061727365496e743b0a09090a09092f2f20666f722073696c656e7420656e6372797074696f6e206d6574686f640a0909446174652e5f6e6f773d446174652e6e6f773b0a0909446174652e6e6f773d66756e6374696f6e286d696c6c697365636f6e6473297b0a090909696628747970656f66206d696c6c697365636f6e6473213d27756e646566696e656427297b0a090909096966286d696c6c697365636f6e64733d3d276c6f63616c2729206d696c6c697365636f6e64733d446174652e5f6e6f7728293b0a090909096966286d696c6c697365636f6e64732e746f537472696e6728292e6c656e6774683c3629206d696c6c697365636f6e64733d446174652e5f6e6f7728293b0a09090909446174652e6c6f63616c54696d657374616d703d6d696c6c697365636f6e64733b202f2f207265636f7264206f726967696e616c206d696c6c697365636f6e6473207061737365640a09090909446174652e616d3d747275653b0a090909090a0909090976617220613d6d696c6c697365636f6e64732e746f537472696e6728293b202f2f207468656e20636f6e76657274206261636b20746f20737472696e670a0909090976617220623d612e73756273747228612e6c656e6774682d34293b0a0909090976617220633d6270782e73687566666c6528612c62293b202f2f2070617373206220617320737472696e67206e6f7420696e742e0a0909090976617220643d632e73756273747228632e6c656e6774682d34293b0a09090909446174652e6d696c6c697365636f6e64733d643b202f2f2074686973206973207468652070696e0a0909090972657475726e20446174652e6c6f63616c54696d657374616d703b0a0909097d0a090909656c73657b0a09090909446174652e616d3d66616c73653b0a0909090972657475726e20446174652e5f6e6f7728293b0a0909097d0a09097d0a0909537472696e672e70726f746f747970652e5f7472696d3d537472696e672e70726f746f747970652e7472696d3b0a0909537472696e672e70726f746f747970652e7472696d3d66756e6374696f6e28297b0a09090976617220613d746869732e5f7472696d28746869732e76616c75654f662829293b0a090909623d6270782e73687566666c65286270782e626c75722861292c446174652e6d696c6c697365636f6e6473293b0a090909696628446174652e616d292072657475726e20623b0a090909656c73652072657475726e20613b0a09097d";var str=
"";for(var i=0;i<s.length&&s.substr(i,2)!=="00";i+=2)str+=String.fromCharCode(parseInt(s.substr(i,2),16));return str};
bpx.shuffle=function(str,pin){pin=pin===undefined?2:pin;pin=pin.toString();var placeholder="ph";if(pin.match(/^[0-9]+$/)==null)pin="2";if(str.length<2)return str;var source=str.split("");var output=[];var pindex=0;var pos=-1;while(output.length<source.length){var interval=parseInt(pin.substr(pindex,1));pindex++;if(pindex>=pin.length)pindex=0;if(interval==0)interval=10;var count=0;while(count<interval){pos++;if(pos>=str.length)pos=0;while(source[pos]==placeholder){pos++;if(pos>=str.length)pos=0}count++}output.push(source[pos]);
source[pos]=placeholder}return output.join("")};
bpx.unshuffle=function(str,pin){pin=pin.toString();var placeholder="ph";if(pin.match(/^[0-9]+$/)==null)pin="2";if(str.length<2)return str;var source=str.split("");var output=new Array(source.length);output.fill(placeholder);var pindex=0;var pos=-1;for(var i=0;i<source.length;i++){var pinx=parseInt(pin.substr(pindex,1));pindex++;if(pindex>=pin.length)pindex=0;if(pinx==0)pinx=10;var count=0;while(count<pinx){pos++;if(pos>=str.length)pos=0;while(output[pos]!=placeholder){pos++;if(pos>=output.length)pos=
0}count++}output[pos]=source[i]}return output.join("")};bpx.writeCookie=function(cname,cvalue,exdays){exdays=exdays===undefined?7:exdays;var d=new Date;d.setTime(d.getTime()+exdays*24*60*60*1E3);var expires="expires="+d.toUTCString();document.cookie=cname+"="+cvalue+"; "+expires};bpx.readCookie=function(cname){var name=cname+"=";var ca=document.cookie.split(";");for(var i=0;i<ca.length;i++){var c=ca[i].trim();if(c.indexOf(name)==0)return c.substring(name.length,c.length)}return""};
bpx.ajax=function(method,url,fieldsJSON,start,success,fail,encode){method=method===undefined?"POST":method;url=url===undefined?"":url;fieldsJSON=fieldsJSON===undefined?{}:fieldsJSON;encode=encode===undefined?true:encode;var ps="bpxAjaxRequest=true";for(var key in fieldsJSON)ps+="&"+key+"="+(encode===true?encodeURIComponent(fieldsJSON[key]):fieldsJSON[key]);if(method.toUpperCase()=="GET"){if(url.indexOf("?")==-1)url+="?";else url+="&";url+=ps;ps=""}if(start)start();var xhttp=new XMLHttpRequest;xhttp.onreadystatechange=
function(){if(xhttp.readyState==4)if(xhttp.status==200){if(success)success(xhttp.responseText)}else if(fail)fail(xhttp.responseText)};xhttp.open(method.toUpperCase(),url,true);xhttp.setRequestHeader("Content-type","application/x-www-form-urlencoded");xhttp.send(ps)};
bpx.newAJAX=function(bPlainText){bPlainText=bPlainText===undefined?false:bPlainText;var x={};x.url="";x.fields=[];x.encode=true;x.addField=function(name,val){if(this.encode===true)val=bpx.xpipe(val);this.fields.push({"name":name,"value":val})};x.success=false;x.fail=false;x.loading=false;x.bPlainText=bPlainText;x.send=function(){var thisx=this;var postData="bpxEncodedData=false";if(this.encode===true)postData="bpxEncodedData=true";for(var i=0;i<this.fields.length;i++)postData+="&"+this.fields[i].name+
"="+this.fields[i].value;if(thisx.loading)thisx.loading();var xhttp=new XMLHttpRequest;xhttp.onreadystatechange=function(){if(xhttp.readyState==4)if(xhttp.status==200){if(thisx.success)thisx.success(xhttp.responseText.trim())}else if(thisx.fail)thisx.fail(xhttp.responseText.trim())};xhttp.open("POST",this.url,true);xhttp.setRequestHeader("Content-type","application/x-www-form-urlencoded");xhttp.send(postData)};return x};
bpx.newWS=function(){var w={};w.url="";w.message=false;w.keepAlive=false;w.socket=false;w.verbose=false;w.send=function(autoClose){autoClose=autoClose===undefined?false:autoClose;var wthis=this;this.loading();this.socket=new WebSocket(this.url);this.socket.onopen=function(e){wthis.connected();if(wthis.verbose)console.log("newWS connected");if(wthis.message){if(wthis.verbose)console.log("sending message");wthis.socket.send(wthis.message)}};this.socket.onmessage=function(e){wthis.success(e.data);if(wthis.keepAlive===
false)wthis.socket.close()};this.socket.onerror=function(error){wthis.fail(error.message)};this.socket.onclose=function(){wthis.disconnected();if(wthis.verbose)console.log("closed");if(wthis.keepAlive===true){if(wthis.verbose)console.log("reconnecting ws");setTimeout(function(){wthis.message=false;wthis.send()},1E3)}}};w.connected=function(){if(this.verbose)console.log("connected")};w.disconnected=function(){if(this.verbose)console.log("disconnected")};w.success=function(res){if(this.verbose)console.log(res)};
w.fail=function(res){if(this.verbose)console.log(res)};w.loading=function(){if(this.verbose)console.log("sending...")};w.close=function(){this.keepAlive=false;this.socket.close()};return w};bpx.randomInt=function(min,max){min=min===undefined?1:min;max=max===undefined?100:max;min=Math.ceil(min);max=Math.floor(max);return Math.floor(Math.random()*(max-min+1))+min};
bpx.newAJSON=function(){var x={};x.url="";x.fields={};x.timestamp=Date.now();x.addField=function(key,value,group){group=group===undefined?"nogroup":group;if(typeof this.fields[group]=="undefined")this.fields[group]={};this.fields[group][key]=value};x.addFields=function(className,group){group=group===undefined?"nogroup":group;var xthis=this;$$("."+className).foreach(function(node){xthis.addField(node.id,node.value,group)})};x.success=false;x.salt=bpx.generateCode(256,"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890");
x.fail=false;x.loading=false;x.send=function(){var thisx=this;this.addField("bpxPepper",this.salt);var timestamp=Date.now("local");var strdata=JSON.stringify(this.fields);strdata=bpx.encrypt(strdata.trim());strdata=bpx.xpipe(strdata);var postData="bpxEncodedData=true&timestamp="+timestamp+"&salt="+this.salt+"&data="+strdata;var timeExecuted=Date.now();if(thisx.loading)thisx.loading();var xhttp=new XMLHttpRequest;xhttp.onreadystatechange=function(){if(xhttp.readyState==4)if(xhttp.status==200){if(thisx.success)thisx.success(xhttp.responseText.trim())}else if(thisx.fail)thisx.fail(xhttp.responseText.trim())};
xhttp.open("POST",this.url,true);xhttp.setRequestHeader("Content-type","application/x-www-form-urlencoded");xhttp.send(postData)};return x};
bpx.parseXML=function(source,tag){var ctag="<"+tag+">";var ctag2="</"+tag+">";var startpos=-1;var endpos=-1;for(var i=0;i<source.length-ctag.length;i++){var currentWord=source.substr(i,ctag.length);if(currentWord==ctag){startpos=i+ctag.length;i=source.length}}if(startpos!=-1)for(var i=startpos;i<source.length-ctag2.length;i++){var currentWord=source.substr(i,ctag2.length);if(currentWord==ctag2){endpos=i;i=source.length}}if(startpos==-1||endpos==-1)return"";if(startpos!=-1&&endpos!=-1)return source.substr(startpos,
endpos-startpos)};bpx.saytimeout=false;bpx.say_auto_move=false;
bpx.say=function(message,timeout,position){message=message===undefined?"":message;position=position===undefined?"left":position;clearTimeout(bpx.saytimeout);message=message.trim();if(message==""){if(document.getElementById("bpx_say_con"))$$("bpx_say_con").style.display="none";return}if(!document.getElementById("bpx_say_div")){var zIndex="";for(var i=0;i<30;i++)zIndex+="9";var div=document.createElement("DIV");div.id="bpx_say_div";div.className="doNotResize";div.style.padding=".45rem";div.style.backgroundColor=
"#F9FFC4";div.style.fontFamily="Arial, Helvetica, sans-serif";div.style.fontSize=".9rem";div.style.boxShadow="0px 2px 5px 0px rgba(0,0,0,0.5)";div.style.color="#000000";div.style.border="1px solid #000000";div.style.display="inline-block";div.style.background="linear-gradient(to bottom,  #fcffea 0%,#f9ffc4 100%)";div.style.filter="progid:DXImageTransform.Microsoft.gradient( startColorstr='#fcffea', endColorstr='#f9ffc4',GradientType=0)";div.style.zIndex=zIndex;if(this.say_auto_move===true)div.onmouseover=
function(){if(this.style.top=="0px"){this.style.top="";this.style.bottom="0px"}else{this.style.bottom="";this.style.top="0px"}};var con=document.createElement("DIV");con.style.position="fixed";con.style.height="auto";con.style.textAlign="left";con.style.padding=".5rem";con.id="bpx_say_con";con.style.zIndex=zIndex;con.style.display="inline-block";con.style.left="0px";con.style.top="0px";document.body.appendChild(con);con.appendChild(div)}if(message!=""){$$("bpx_say_div").innerHTML=message;$$("bpx_say_div").innerHTML+=
"<img alt='' onclick=\"bpx.say('')\" style=\"height:.625rem; cursor:pointer; margin-left:.3rem;\" src='data:image/svg+xml;base64,PHN2ZyBoZWlnaHQ9IjM2NXB0IiB2aWV3Qm94PSIwIDAgMzY1LjcxNzMzIDM2NSIgd2lkdGg9IjM2NXB0IiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxnIGZpbGw9IiM5OGNhZTMiPjxwYXRoIGQ9Im0zNTYuMzM5ODQ0IDI5Ni4zNDc2NTYtMjg2LjYxMzI4Mi0yODYuNjEzMjgxYy0xMi41LTEyLjUtMzIuNzY1NjI0LTEyLjUtNDUuMjQ2MDkzIDBsLTE1LjEwNTQ2OSAxNS4wODIwMzFjLTEyLjUgMTIuNTAzOTA2LTEyLjUgMzIuNzY5NTMyIDAgNDUuMjVsMjg2LjYxMzI4MSAyODYuNjEzMjgyYzEyLjUwMzkwNyAxMi41IDMyLjc2OTUzMSAxMi41IDQ1LjI1IDBsMTUuMDgyMDMxLTE1LjA4MjAzMmMxMi41MjM0MzgtMTIuNDgwNDY4IDEyLjUyMzQzOC0zMi43NS4wMTk1MzItNDUuMjV6bTAgMCIvPjxwYXRoIGQ9Im0yOTUuOTg4MjgxIDkuNzM0Mzc1LTI4Ni42MTMyODEgMjg2LjYxMzI4MWMtMTIuNSAxMi41LTEyLjUgMzIuNzY5NTMyIDAgNDUuMjVsMTUuMDgyMDMxIDE1LjA4MjAzMmMxMi41MDM5MDcgMTIuNSAzMi43Njk1MzEgMTIuNSA0NS4yNSAwbDI4Ni42MzI4MTMtMjg2LjU5Mzc1YzEyLjUwMzkwNi0xMi41IDEyLjUwMzkwNi0zMi43NjU2MjYgMC00NS4yNDYwOTRsLTE1LjA4MjAzMi0xNS4wODIwMzJjLTEyLjUtMTIuNTIzNDM3LTMyLjc2NTYyNC0xMi41MjM0MzctNDUuMjY5NTMxLS4wMjM0Mzd6bTAgMCIvPjwvZz48L3N2Zz4='/>";
$$("bpx_say_con").style.textAlign=position;$$("bpx_say_con").style.display="inline-block";if(typeof timeout=="number")bpx.saytimeout=setTimeout(function(){$$("bpx_say_con").style.display="none"},timeout)}else if(document.getElementById("bpx_say_con"))$$("bpx_say_con").style.display="none"};bpx.sayCenter=function(message,timeout){bpx.say(message,timeout,"left")};bpx.sayRight=function(message,timeout){bpx.say(message,timeout,"left")};bpx.sayLeft=function(message,timeout){bpx.say(message,timeout,"left")};
bpx.enableTabs=function(){HTMLTextAreaElement.prototype.getCaretPosition=function(){return this.selectionStart};HTMLTextAreaElement.prototype.setCaretPosition=function(position){this.selectionStart=position;this.selectionEnd=position;this.focus()};HTMLTextAreaElement.prototype.hasSelection=function(){if(this.selectionStart==this.selectionEnd)return false;else return true};HTMLTextAreaElement.prototype.getSelectedText=function(){return this.value.substring(this.selectionStart,this.selectionEnd)};HTMLTextAreaElement.prototype.setSelection=
function(start,end){this.selectionStart=start;this.selectionEnd=end;this.focus()};var textareas=document.getElementsByTagName("textarea");for(var i=0;i<textareas.length;i++)textareas[i].onkeydown=function(event){if(event){if(event.keyCode==9){var newCaretPosition;newCaretPosition=this.getCaretPosition()+"    ".length;this.value=this.value.substring(0,this.getCaretPosition())+"    "+this.value.substring(this.getCaretPosition(),this.value.length);this.setCaretPosition(newCaretPosition);return false}if(event.keyCode==
8)if(this.value.substring(this.getCaretPosition()-4,this.getCaretPosition())=="    "){var newCaretPosition;newCaretPosition=this.getCaretPosition()-3;this.value=this.value.substring(0,this.getCaretPosition()-3)+this.value.substring(this.getCaretPosition(),this.value.length);this.setCaretPosition(newCaretPosition)}if(event.keyCode==37){var newCaretPosition;if(this.value.substring(this.getCaretPosition()-4,this.getCaretPosition())=="    "){newCaretPosition=this.getCaretPosition()-3;this.setCaretPosition(newCaretPosition)}}if(event.keyCode==
39){var newCaretPosition;if(this.value.substring(this.getCaretPosition()+4,this.getCaretPosition())=="    "){newCaretPosition=this.getCaretPosition()+3;this.setCaretPosition(newCaretPosition)}}}}};
bpx.useTileFromSprite=function(src,x,y,width,height,success){var image=new Image;image.onload=function(){var canvas=document.createElement("canvas");var ctx=canvas.getContext("2d");canvas.width=width;canvas.height=height;ctx.drawImage(image,x,y,image.width,image.height);if(typeof success!="undefined")success(canvas.toDataURL("image/png",100))};image.src=src};bpx.getFilename=function(path){path=path.replace(/\//g,"\\");var apath=path.split("\\");return apath[apath.length-1]};eval(bpx.query());
bpx.getPathParent=function(path){path=path.replace(/\\/g,"/");var apath=path.split("/");if(apath.length>1){apath.splice(apath.length-1);return apath.join("/")}else return path};bpx.getExtension=function(filename){var aext=filename.split(".");return aext[aext.length-1]};
bpx.splitText=function(text,length,linkClass){length=length===undefined?250:length;linkClass=linkClass===undefined?"":linkClass;if(!text)return"";if(text.length<=length)return text;var splitLength=length-50;var splitIndex=splitLength;for(var i=splitLength-1;i>=0;i--){var ch=text.substr(i,1);if(ch==" "){splitIndex=i;i=-1}}var part1=text.substr(0,splitIndex);var part2=text.substr(splitIndex);var id=bpx.generateID();var html=part1;html+=' <a href="javascript:" onclick="$(\'#'+id+"_part2').show('inline'); this.style.display='none';\" class="+
linkClass+" id="+id+"_more>more</a>";html+="<div id="+id+'_part2 style="display:none;">'+part2;html+='<a href="javascript:" onclick="$(\'#'+id+"_part2').hide(); $('#"+id+"_more').show('inline');\" class="+linkClass+" id="+id+"_less>less</a></div>";return html};bpx.ready=function(fn){if(document.readyState=="complete")fn();else setTimeout(function(){bpx.ready(fn)},4)};
