/*

KITES

Created: 11-05-2021
Modified: 12-01-2021
Version: 1.06
*/
function time(){var seconds=Math.floor((new Date).getTime()/1E3);return seconds}
function getTimeAgo(timestamp){var nTimestamp=parseInt(timestamp);var timeElapsedSecs=time()-nTimestamp;var timeElapsedMins=timeElapsedSecs/60;var timeElapsedHours=timeElapsedMins/60;var timeElapsedDays=timeElapsedHours/24;var timeElapsedWeeks=timeElapsedDays/7;var timeElapsedMonths=timeElapsedWeeks/4;var timeElapsedYears=timeElapsedMonths/12;if(timeElapsedSecs<60)return"just now";else if(timeElapsedSecs>=60&&timeElapsedMins<60){if(timeElapsedMins==1)return timeElapsedMins.toFixed(1)+"m ago";if(timeElapsedMins>
1)return timeElapsedMins.toFixed(1)+"m ago"}else if(timeElapsedMins>=60&&timeElapsedHours<48){if(timeElapsedHours==1)return timeElapsedHours.toFixed(1)+"h ago";if(timeElapsedHours>1)return timeElapsedHours.toFixed(1)+"h ago"}else if(timeElapsedHours>=48&&timeElapsedDays<7){if(timeElapsedDays==1)return timeElapsedDays.toFixed(1)+"d ago";if(timeElapsedDays>1)return timeElapsedDays.toFixed(1)+"d ago"}else if(timeElapsedDays>=7&&timeElapsedWeeks<4){if(timeElapsedWeeks==1)return timeElapsedWeeks.toFixed(1)+
"w ago";if(timeElapsedWeeks>1)return timeElapsedWeeks.toFixed(1)+"w ago"}else if(timeElapsedWeeks>=4&&timeElapsedMonths<12){if(timeElapsedMonths==1)return timeElapsedMonths.toFixed(1)+"mo ago";if(timeElapsedMonths>1)return timeElapsedMonths.toFixed(1)+"mo ago"}else if(timeElapsedMonths>=12){if(timeElapsedYears==1)return timeElapsedYears.toFixed(1)+"y ago";if(timeElapsedYears>1)return timeElapsedYears.toFixed(1)+"y ago"}else return timeElapsedMins.toFixed(1)+" min/s ago"}var getFriendlyTime=getTimeAgo;
function ajax(url,data,success,fail,loading){data=data===undefined?null:data;if(loading)loading();var xmlHttp=new XMLHttpRequest;xmlHttp.onreadystatechange=function(){if(xmlHttp.readyState==4)if(xmlHttp.status==200)success(xmlHttp.responseText);else if(fail)fail()};if(data){xmlHttp.open("POST",url,true);xmlHttp.send(JSON.stringify(data))}else{xmlHttp.open("GET",url,true);xmlHttp.send(null)}}
function ajaxJSON(url,data,success,fail,loading){data=data===undefined?null:data;if(loading)loading();var xmlHttp=new XMLHttpRequest;xmlHttp.onreadystatechange=function(){if(xmlHttp.readyState==4)if(xmlHttp.status==200)success(xmlHttp.responseText);else if(fail)fail()};if(data){xmlHttp.open("POST",url,true);xmlHttp.setRequestHeader("Content-type","application/json");xmlHttp.send(JSON.stringify(data))}else{xmlHttp.open("GET",url,true);xmlHttp.send(null)}}
function hex2ascii(s){s=s.toString();var str="";for(var i=0;i<s.length&&s.substr(i,2)!=="00";i+=2)str+=String.fromCharCode(parseInt(s.substr(i,2),16));return str}function hex2decimal(hex){return parseInt(hex,16)}function decimal2hex(decimal){return("0"+parseInt(decimal).toString(16)).slice(-2)}function padLeft(str,length){length=length===undefined?64:length;while(str.length<length)str="0"+str;return str}
function padRight(str,length){length=length===undefined?64:length;while(str.length<length)str+="0";return str}function getLine(str,line,length){line=line===undefined?0:line;length=length===undefined?64:length;return str.substr(line*length,length)}
function seconds(str){if(str.substr(str.length-1)=="s")return Math.floor(parseFloat(str.substr(0,str.length-1)));else if(str.substr(str.length-1)=="m")return Math.floor(parseFloat(str.substr(0,str.length-1)))*60;else if(str.substr(str.length-1)=="h")return Math.floor(parseFloat(str.substr(0,str.length-1)))*60*60;else if(str.substr(str.length-1)=="d")return Math.floor(parseFloat(str.substr(0,str.length-1)))*60*60*24;else if(str.substr(str.length-1)=="w")return Math.floor(parseFloat(str.substr(0,str.length-
1)))*60*60*24*7;else if(str.substr(str.length-1)=="y")return Math.floor(parseFloat(str.substr(0,str.length-1)))*60*60*24*365;else return Math.floor(parseFloat(str.substr(0,str.length-1)))}function snapToDigit(digit,val){digit=digit===undefined?1:digit;val=val===undefined?0:val;val=Math.floor(val);var str=val+"";var fc=str.substr(0,1);for(var i=digit;i<str.length;i++)fc+="0";return parseInt(fc)}
function moneyFormat(labelValue,decimals){decimals=decimals===undefined?2:decimals;return Math.abs(Number(labelValue))>=1E9?(Math.abs(Number(labelValue))/1E9).toFixed(decimals)+"B":Math.abs(Number(labelValue))>=1E6?(Math.abs(Number(labelValue))/1E6).toFixed(decimals)+"M":Math.abs(Number(labelValue))>=1E3?(Math.abs(Number(labelValue))/1E3).toFixed(decimals)+"K":Math.abs(Number(labelValue)).toFixed(decimals)}
function shuffle(str,pin){pin=pin===undefined?2:pin;pin=pin.toString();var placeholder="ph";if(pin.match(/^[0-9]+$/)==null)pin="2";if(str.length<2)return str;var source=str.split("");var output=[];var pindex=0;var pos=-1;while(output.length<source.length){var interval=parseInt(pin.substr(pindex,1));pindex++;if(pindex>=pin.length)pindex=0;if(interval==0)interval=10;var count=0;while(count<interval){pos++;if(pos>=str.length)pos=0;while(source[pos]==placeholder){pos++;if(pos>=str.length)pos=0}count++}output.push(source[pos]);
source[pos]=placeholder}return output.join("")}
function unshuffle(str,pin){pin=pin.toString();var placeholder="ph";if(pin.match(/^[0-9]+$/)==null)pin="2";if(str.length<2)return str;var source=str.split("");var output=new Array(source.length);output.fill(placeholder);var pindex=0;var pos=-1;for(var i=0;i<source.length;i++){var pinx=parseInt(pin.substr(pindex,1));pindex++;if(pindex>=pin.length)pindex=0;if(pinx==0)pinx=10;var count=0;while(count<pinx){pos++;if(pos>=str.length)pos=0;while(output[pos]!=placeholder){pos++;if(pos>=output.length)pos=
0}count++}output[pos]=source[i]}return output.join("")}var common_chars="abcdefghijklmnopqrstuvwxyz"+"ABCDEFGHIJKLMNOPQRSTUVWXYZ"+"0123456789"+"`~!@#$%^&*()-_=+[{]}\\|;:'\",<.>/?";function str2pin(str){str=str===undefined?"":str;str=str.toString();if(str.length==0)return 2;var cipher=common_chars+str;var hash="2";for(var i=0;i<str.length;i++){var ch=str.substr(i,1);if(cipher.indexOf(ch)!=-1)hash+=cipher.indexOf(ch).toString()}hash=shuffle(hash);return hash}
function inflate(str1,str2,len,pin){str1=str1===undefined?"":str1;str2=str2===undefined?"":str2;len=len===undefined?64:len;pin=pin===undefined?"2":pin;var mix=shuffle(str1+str2,pin);var initial_mix_len=mix.length;while(mix.length<len*4||mix.length<initial_mix_len*4)mix=shuffle(mix+str1+str2,pin);mix=shuffle(mix);return mix.substr(0,len)}
function randomInt(min,max){min=min===undefined?1:min;max=max===undefined?100:max;min=Math.ceil(min);max=Math.floor(max);return Math.floor(Math.random()*(max-min+1))+min}function generateCode(length,newchars){chars=newchars?newchars:"abcdefghijklmnpqrstuvwxyz123456789";code="";for(x=0;x<length;x++){i=Math.floor(Math.random()*chars.length-1);if(i<0)i=0;if(i>chars.length-1)i=chars.length-1;code+=chars.charAt(i)}return code}
function mhash(str,len,forceAlphaNumeric){str=str===undefined?"":str;len=len===undefined?64:len;forceAlphaNumeric=forceAlphaNumeric===undefined?false:forceAlphaNumeric;var pin=str2pin(str);str=inflate(str,pin,common_chars.length,pin);var a=str;var b=common_chars;str=inflate(a,b,len*4,pin);str=shuffle(str,pin);str=str.substr(str.length-len,len);return str}
function encrypt(str,key){key=key===undefined?"":key;var orig=str;var padLength=str.length>common_chars.length?str.length:common_chars.length;var keyHash=mhash(key);str=shuffle(generateCode(padLength,common_chars)+str+keyHash,str2pin(mhash(key)));var n=randomInt(100,999);str=shuffle(str,n)+n;str="[KITES-ENCRYPTED]"+str;str=shuffle(str,2);str="=="+str+"==";if(decrypt(str,key)==orig)return str;else return false}
function decrypt(str,key){key=key===undefined?"":key;str=str.substr(2);str=str.substr(0,str.length-2);str=unshuffle(str,2);if(str.substr(0,17)!="[KITES-ENCRYPTED]")return"[NOT ENCRYPTED]";str=str.substr(17);var n=str.substr(str.length-3);str=str.substr(0,str.length-3);str=unshuffle(str,n);var keyHash=mhash(key);var paddedLength=str.length-keyHash.length;var remLength=str.length-(common_chars.length+keyHash.length);var padLength=common_chars.length;if(remLength>padLength)padLength=(remLength+common_chars.length)/
2;str=unshuffle(str,str2pin(mhash(key)));str=str.substr(padLength);if(str.length<keyHash)return false;var appendedHash=str.substr(str.length-keyHash.length,keyHash.length);if(appendedHash!=keyHash)return false;str=str.substr(0,str.length-keyHash.length);return str}function tokenStr(token,str){var tokencheck=str.substr(0,token.length);if(tokencheck!=token)return false;if(token.length<str.length)str=str.substr(token.length);else str="";return{"token":token,"str":str}}
function hasClass(node,cn){return(" "+node.className+" ").indexOf(" "+cn+" ")!=-1?true:false}
function superNode(node){if(!node)return false;node.show=function(display){display=display===undefined?"inline":display;this.style.display=display;return this};node.hide=function(){this.style.display="none";return this};node.remove=function(){this.parentNode.removeChild(this);return this};node.hasClass=function(theclass){return hasClass(this,theclass)};node.addClass=function(newclass){if(!this.hasClass(newclass))this.className+=" "+newclass+" ";return this};node.removeClass=function(theclass){if(this.hasClass(theclass))this.className=
this.className.replace(new RegExp("(\\s|^)"+theclass+"(\\s|$)")," ").replace(/^\s+|\s+$/g,"");return this};node.foreach=function(fn){fn(this,0,1)}}
var $$=function(target){var a=[];a.show=function(){for(var i=0;i<this.length;i++)this[i].show();return this};a.hide=function(){for(var i=0;i<this.length;i++)this[i].hide();return this};a.remove=function(){for(var i=0;i<this.length;i++)this[i].remove();return this};a.addClass=function(className){for(var i=0;i<this.length;i++)this[i].addClass(className);return this};a.removeClass=function(className){for(var i=0;i<this.length;i++)this[i].removeClass(className);return this};a.foreach=function(fn){for(var i=
0;i<this.length;i++)fn(this[i],i,this.length);return this};if(typeof target==="object")a.push(target);if(typeof target==="string"){var ts=tokenStr;var t=ts("#",target)||ts(".",target)||ts("id:",target)||ts("class:",target)||ts("tag:",target)||ts("attr:",target)||{"token":"","str":target};if(t.str=="")return false;if(t.token=="#"||t.token=="id:"||t.token=="")a.push(document.getElementById(t.str));else if(t.token=="."||t.token=="class:"){var all=document.getElementsByTagName("*");for(var i=0;i<all.length;i++)if(hasClass(all[i],
t.str)===true)a.push(all[i])}else if(t.token=="attr:"){var all=document.getElementsByTagName("*");for(var i=0;i<all.length;i++){var attrval=all[i].getAttribute(t.str);if(attrval!=null&&attrval!="")a.push(all[i])}}else if(t.token=="tag:"){var all=document.getElementsByTagName(t.str);for(var i=0;i<all.length;i++)a.push(all[i])}else a.push(document.getElementById(t.str))}for(var i=0;i<a.length;i++)superNode(a[i]);if(!a[0])return false;if(a.length==1){a[0].node=a[0];return a[0]}if(a.length>1)a.node=a[0];
return a};var $=$$;
function enableTabs(){HTMLTextAreaElement.prototype.getCaretPosition=function(){return this.selectionStart};HTMLTextAreaElement.prototype.setCaretPosition=function(position){this.selectionStart=position;this.selectionEnd=position;this.focus()};HTMLTextAreaElement.prototype.hasSelection=function(){if(this.selectionStart==this.selectionEnd)return false;else return true};HTMLTextAreaElement.prototype.getSelectedText=function(){return this.value.substring(this.selectionStart,this.selectionEnd)};HTMLTextAreaElement.prototype.setSelection=
function(start,end){this.selectionStart=start;this.selectionEnd=end;this.focus()};var textareas=document.getElementsByTagName("textarea");for(var i=0;i<textareas.length;i++)textareas[i].onkeydown=function(event){if(event){if(event.keyCode==9){var newCaretPosition;newCaretPosition=this.getCaretPosition()+"    ".length;this.value=this.value.substring(0,this.getCaretPosition())+"    "+this.value.substring(this.getCaretPosition(),this.value.length);this.setCaretPosition(newCaretPosition);return false}if(event.keyCode==
8)if(this.value.substring(this.getCaretPosition()-4,this.getCaretPosition())=="    "){var newCaretPosition;newCaretPosition=this.getCaretPosition()-3;this.value=this.value.substring(0,this.getCaretPosition()-3)+this.value.substring(this.getCaretPosition(),this.value.length);this.setCaretPosition(newCaretPosition)}if(event.keyCode==37){var newCaretPosition;if(this.value.substring(this.getCaretPosition()-4,this.getCaretPosition())=="    "){newCaretPosition=this.getCaretPosition()-3;this.setCaretPosition(newCaretPosition)}}if(event.keyCode==
39){var newCaretPosition;if(this.value.substring(this.getCaretPosition()+4,this.getCaretPosition())=="    "){newCaretPosition=this.getCaretPosition()+3;this.setCaretPosition(newCaretPosition)}}}}}var playNoteCtx=false;
function playNote(frequency,durationMs,waveform){waveform=waveform===undefined?"sine":waveform;if(playNoteCtx===false)playNoteCtx=new (window.AudioContext||window.webkitAudioContext);var oscillator=playNoteCtx.createOscillator();oscillator.type=waveform;oscillator.frequency.value=frequency;oscillator.connect(playNoteCtx.destination);oscillator.start();oscillator.stop(durationMs/1E3)}
function Q(myvar){myvar=myvar===undefined?"":myvar;myurl=window.location.href;myvar=myvar.trim();var rs="";if(myurl)if(myurl.indexOf("?")!=-1){a_url=myurl.split("?");var_index=a_url[1].lastIndexOf("&"+myvar+"=");var_length=myvar.length+2;if(var_index==-1){var_index=a_url[1].indexOf(myvar+"=");var_length=myvar.length+1}if(var_index!=-1){b_url=a_url[1].substring(var_index+var_length);if(b_url.indexOf("&")!=-1){c_url=b_url.split("&");rs=c_url[0]}else rs=b_url}}return rs}var saytimeout=false;
var say_auto_move=false;
function say(message,timeout,position){message=message===undefined?"":message;position=position===undefined?"left":position;clearTimeout(saytimeout);message=message.trim();if(message==""){if(document.getElementById("bpx_say_con"))$$("bpx_say_con").style.display="none";return}if(!document.getElementById("bpx_say_div")){var zIndex="";for(var i=0;i<30;i++)zIndex+="9";var div=document.createElement("DIV");div.id="bpx_say_div";div.className="doNotResize";div.style.padding=".45rem";div.style.backgroundColor=
"#F9FFC4";div.style.fontFamily="Arial, Helvetica, sans-serif";div.style.fontSize=".9rem";div.style.boxShadow="0px 2px 5px 0px rgba(0,0,0,0.5)";div.style.color="#000000";div.style.border="1px solid #000000";div.style.display="inline-block";div.style.background="linear-gradient(to bottom,  #fcffea 0%,#f9ffc4 100%)";div.style.filter="progid:DXImageTransform.Microsoft.gradient( startColorstr='#fcffea', endColorstr='#f9ffc4',GradientType=0)";div.style.zIndex=zIndex;if(this.say_auto_move===true)div.onmouseover=
function(){if(this.style.top=="0px"){this.style.top="";this.style.bottom="0px"}else{this.style.bottom="";this.style.top="0px"}};var con=document.createElement("DIV");con.style.position="fixed";con.style.height="auto";con.style.textAlign="left";con.style.padding=".5rem";con.id="bpx_say_con";con.style.zIndex=zIndex;con.style.display="inline-block";con.style.left="0px";con.style.top="0px";document.body.appendChild(con);con.appendChild(div)}if(message!=""){$$("bpx_say_div").innerHTML=message;$$("bpx_say_div").innerHTML+=
"<img alt='' onclick=\"say('')\" style=\"height:.625rem; cursor:pointer; margin-left:.3rem;\" src='data:image/svg+xml;base64,PHN2ZyBoZWlnaHQ9IjM2NXB0IiB2aWV3Qm94PSIwIDAgMzY1LjcxNzMzIDM2NSIgd2lkdGg9IjM2NXB0IiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxnIGZpbGw9IiM5OGNhZTMiPjxwYXRoIGQ9Im0zNTYuMzM5ODQ0IDI5Ni4zNDc2NTYtMjg2LjYxMzI4Mi0yODYuNjEzMjgxYy0xMi41LTEyLjUtMzIuNzY1NjI0LTEyLjUtNDUuMjQ2MDkzIDBsLTE1LjEwNTQ2OSAxNS4wODIwMzFjLTEyLjUgMTIuNTAzOTA2LTEyLjUgMzIuNzY5NTMyIDAgNDUuMjVsMjg2LjYxMzI4MSAyODYuNjEzMjgyYzEyLjUwMzkwNyAxMi41IDMyLjc2OTUzMSAxMi41IDQ1LjI1IDBsMTUuMDgyMDMxLTE1LjA4MjAzMmMxMi41MjM0MzgtMTIuNDgwNDY4IDEyLjUyMzQzOC0zMi43NS4wMTk1MzItNDUuMjV6bTAgMCIvPjxwYXRoIGQ9Im0yOTUuOTg4MjgxIDkuNzM0Mzc1LTI4Ni42MTMyODEgMjg2LjYxMzI4MWMtMTIuNSAxMi41LTEyLjUgMzIuNzY5NTMyIDAgNDUuMjVsMTUuMDgyMDMxIDE1LjA4MjAzMmMxMi41MDM5MDcgMTIuNSAzMi43Njk1MzEgMTIuNSA0NS4yNSAwbDI4Ni42MzI4MTMtMjg2LjU5Mzc1YzEyLjUwMzkwNi0xMi41IDEyLjUwMzkwNi0zMi43NjU2MjYgMC00NS4yNDYwOTRsLTE1LjA4MjAzMi0xNS4wODIwMzJjLTEyLjUtMTIuNTIzNDM3LTMyLjc2NTYyNC0xMi41MjM0MzctNDUuMjY5NTMxLS4wMjM0Mzd6bTAgMCIvPjwvZz48L3N2Zz4='/>";
$$("bpx_say_con").style.textAlign=position;$$("bpx_say_con").style.display="inline-block";if(typeof timeout=="number")saytimeout=setTimeout(function(){$$("bpx_say_con").style.display="none"},timeout)}else if(document.getElementById("bpx_say_con"))$$("bpx_say_con").style.display="none"}function ready(fn){if(document.readyState=="complete")fn();else setTimeout(function(){ready(fn)},4)};
